### ISSUE TITLE
Migrate repo?

### ISSUE THREAD

**Issue by roughani** [wleddy/bikeandwalk#35]
@wleddy and @seamus0g: let me know if you guys want to work out of this repository (I added both of you as admins):
https://github.com/code4sac/bikeandwalk/

I can migrate the open issues using this tool:
https://github-issue-mover.appspot.com/

Here's an example of what that would look like:
https://github.com/code4sac/bikeandwalk/issues/1

Totally cool if you guys prefer to stay in this repo.

**Comment by seamus0g** [comment]
Thanks Ash, I have migrated to the new repo.

jr

**Comment by roughani** [comment]
Just migrated all of the open issues to the new repo.
